# Generated by Django 5.2.5 on 2025-12-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpenalty',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
