# Generated by Django 5.2.5 on 2026-01-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_userpenalty_blocked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='facilities',
            field=models.TextField(blank=True, help_text='Comma-separated facilities', null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='has_cafe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='has_parking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='has_restroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='is_open_24_7',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='operating_hours',
            field=models.CharField(default='24/7', max_length=100),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
