# Generated by Django 6.0.1 on 2026-02-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_recentlyviewedstation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='stationrating',
            name='helpful_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stationrating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
