# Generated by Django 6.0.2 on 2026-02-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_alter_stationrating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
