from django.urls import path
from .views import (
    login_view, 
    signup_view,
    select_car, 
    stations_view,
    dashboard_view,
    bookings_view,
    profile_view,
    favorites_view,
    peer_chargers_view,
    book_station_view,
    logout_view,
    ranking_view,
    route_map_view,
    home_view,
    geocode_view,
    station_detail_view,
    analytics_view,
    charging_session_view,
    admin_dashboard_view,
)

urlpatterns = [
    path("", login_view, name="login"),
    path("home/", home_view, name="home"),
    path("signup/", signup_view, name="signup"),
    path("logout/", logout_view, name="logout"),
    path("select-car/", select_car, name="select_car"),
    path("stations/", stations_view, name="stations"),
    path("station-detail/", station_detail_view, name="station_detail"),
    path("ranking/", ranking_view, name="ranking"),
    path("route-map/", route_map_view, name="route_map"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("bookings/", bookings_view, name="bookings"),
    path("profile/", profile_view, name="profile"),
    path("favorites/", favorites_view, name="favorites"),
    path("peer-chargers/", peer_chargers_view, name="peer_chargers"),
    path("book/<int:station_id>/", book_station_view, name="book_station"),
    path("geocode/", geocode_view, name="geocode"),
    path("analytics/", analytics_view, name="analytics"),
    path("charging-session/", charging_session_view, name="charging_session"),
    path("staff-dashboard/", admin_dashboard_view, name="admin_dashboard"),
]
